# Generated by Django 2.0.4 on 2018-05-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20180507_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='feature',
            field=models.CharField(choices=[('feat_1', 'Feature 1'), ('feat_2', 'Feature 2'), ('feat_3', 'Feature 3'), ('feat_4', 'Feature 4'), ('no_feature', 'No feature')], default=True, max_length=20),
        ),
    ]
