# Generated by Django 2.0.4 on 2018-05-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicepage_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='feature',
            field=models.CharField(choices=[('feat_1', 'Feature 1'), ('feat_2', 'Feature 2'), ('feat_3', 'Feature 3'), ('feat_4', 'Feature 4'), ('no_feature', 'No feature')], default='no_feature', max_length=20),
        ),
    ]
