# Generated by Django 2.0.4 on 2018-05-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20180509_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='feature',
            field=models.CharField(choices=[(1, 'Feature 1'), (2, 'Feature 2'), (3, 'Feature 3'), (4, 'Feature 4'), (0, 'No feature')], default='no_feature', max_length=20),
        ),
    ]
