# Generated by Django 2.0.4 on 2018-05-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20180509_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='feature',
            field=models.IntegerField(choices=[(1, 'Feature 1'), (2, 'Feature 2'), (3, 'Feature 3'), (4, 'Feature 4'), (0, 'No feature')], default=0),
        ),
    ]
