# Generated by Django 2.0.4 on 2018-06-07 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_servicepage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='display_price',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
