# Generated by Django 2.0.4 on 2018-06-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_serviceindexpage_google_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceindexpage',
            name='google_map',
        ),
    ]
