# Generated by Django 2.0.4 on 2018-06-08 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_remove_serviceindexpage_google_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceindexpage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone must be entered in the format (555) 567-8555', regex='(\\(\\d\\d\\d\\)) (\\d\\d\\d-\\d\\d\\d\\d)')]),
        ),
    ]
