# Generated by Django 2.0.4 on 2018-06-08 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_serviceindexpage_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceindexpage',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter in the format (555) 123 4567', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone must be entered in the format (555) 567-8555', regex='(\\(\\d\\d\\d\\)) (\\d\\d\\d-\\d\\d\\d\\d)')]),
        ),
    ]
