# Generated by Django 2.0.4 on 2018-04-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpage_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogindexpage',
            options={'verbose_name': 'blog indexpage'},
        ),
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'blogpage'},
        ),
        migrations.AlterModelOptions(
            name='blogpagegalleryimage',
            options={'verbose_name': 'blogpage gallery image'},
        ),
        migrations.AlterModelOptions(
            name='blogpagetag',
            options={'verbose_name': 'blogpage tag'},
        ),
        migrations.AlterModelOptions(
            name='blogtagindexpage',
            options={'verbose_name': 'blogtag indexpage'},
        ),
    ]
