# Generated by Django 2.0.4 on 2018-04-19 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180419_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='blogpagegalleryimage',
            options={'ordering': ['sort_order']},
        ),
    ]
