# Generated by Django 2.0.4 on 2018-05-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blogpage_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='feature',
            field=models.IntegerField(choices=[(1, 'Feature 1'), (2, 'Feature 2'), (3, 'Feature 3'), (4, 'Feature 4'), (5, 'Feature 5'), (6, 'Feature 6'), (0, 'No feature')], default=0),
        ),
    ]
