# Generated by Django 2.0.4 on 2018-04-19 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0002_auto_20180418_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photogalleryindexpage',
            options={'verbose_name': 'photo gallery indexpage'},
        ),
    ]
