# Generated by Django 2.0.4 on 2018-05-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0003_auto_20180419_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallerypage',
            name='feature',
            field=models.IntegerField(choices=[(1, 'Feature 1'), (2, 'Feature 2'), (3, 'Feature 3'), (0, 'No feature')], default=0),
        ),
    ]
