# Generated by Django 2.0.4 on 2018-07-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_people_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='about',
            field=models.TextField(max_length=300),
        ),
    ]
