# Generated by Django 2.0.4 on 2018-04-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepageimagegallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageimagegallery',
            name='logo',
            field=models.BooleanField(default=False),
        ),
    ]
