# Generated by Django 2.0.4 on 2018-04-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepagelogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagelogo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homepagelogo',
            name='page',
        ),
        migrations.DeleteModel(
            name='HomePageLogo',
        ),
    ]
