# Generated by Django 2.0.4 on 2018-04-19 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180418_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'homepage'},
        ),
    ]
