# Generated by Django 2.0.4 on 2018-05-11 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20180507_2058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterText',
        ),
    ]
