# Generated by Django 2.0.4 on 2018-06-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_delete_footertext'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='phone_number',
            field=models.IntegerField(default=5555555555),
        ),
    ]
