# Generated by Django 2.0.4 on 2018-06-07 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_homepage_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone must be entered in the format (555) 567-8555', regex='(\\(\\d\\d\\d\\)) (\\d\\d\\d-\\d\\d\\d\\d)')]),
        ),
    ]
