# Generated by Django 2.0.4 on 2018-04-19 22:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0040_page_draft_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutIndexPage',
            new_name='AboutPage',
        ),
    ]
