# Generated by Django 2.0.4 on 2018-04-19 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20180419_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'aboutpage'},
        ),
    ]
