# Generated by Django 2.0.4 on 2018-04-19 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0004_contactpage_servicepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'dog servicepage',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameModel(
            old_name='ServicePage',
            new_name='CatServicePage',
        ),
        migrations.AlterModelOptions(
            name='catservicepage',
            options={'verbose_name': 'cat servicepage'},
        ),
    ]
